/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Produtividade API
 * API de produtividade para gestão de produtividade dos funcionários dentro do armazém e gestão de carregamento
 * OpenAPI spec version: 1.0
 */
import {
  z as zod
} from 'zod';


/**
 * @summary Iniciar demanda de produtividade
 */
export const iniciarDemandaProdutividadeParams = zod.object({
  "centerId": zod.string()
})

export const iniciarDemandaProdutividadeBody = zod.object({
  "inicio": zod.iso.datetime({}).describe('Data e hora de início da demanda'),
  "processo": zod.string().describe('Processo que está sendo iniciado'),
  "funcionarioId": zod.string().describe('ID do funcionário que está iniciando o picking'),
  "paletesIds": zod.array(zod.string()).describe('IDs das paletes que estão sendo iniciadas'),
  "centerId": zod.string().describe('ID do centro que está iniciando o picking'),
  "turno": zod.string().describe('Turno que está iniciando o picking'),
  "obs": zod.string().describe('Observação do picking')
})

/**
 * @summary Finaliza um picking
 */
export const produtividadeControllerFinalizarPickingParams = zod.object({
  "palletId": zod.string()
})

export const produtividadeControllerFinalizarPickingBody = zod.object({
  "observacao": zod.string().describe('Observação da finalização')
})

/**
 * @summary Adiciona uma pausa individual
 */
export const produtividadeControllerAddPausaIndividualBody = zod.object({
  "paleteId": zod.string().describe('ID do pallet que está sendo pausado'),
  "motivo": zod.string().describe('Motivo da pausa'),
  "descricao": zod.string().describe('Descrição da pausa')
})

/**
 * @summary Finaliza uma pausa individual
 */
export const produtividadeControllerFinalizarPausaIndividualParams = zod.object({
  "palletId": zod.string()
})

/**
 * @summary Deleta uma demanda
 */
export const deletarDemandaParams = zod.object({
  "palletId": zod.string()
})

/**
 * @summary Adiciona uma pausa geral
 */
export const produtividadeControllerAddPausaGeralBody = zod.object({
  "centerId": zod.string().describe('ID do centro que está sendo pausado'),
  "turno": zod.string().describe('Turno da pausa geral'),
  "processo": zod.string().describe('Processo da pausa geral'),
  "segmento": zod.string().describe('Segmento da pausa geral'),
  "motivo": zod.string().describe('Motivo da pausa geral')
})

/**
 * @summary Finaliza uma pausa geral
 */
export const produtividadeControllerFinalizarPausaGeralBody = zod.object({
  "centerId": zod.string().describe('ID do centro que está sendo pausado'),
  "turno": zod.string().describe('Turno da pausa geral'),
  "processo": zod.string().describe('Processo da pausa geral'),
  "segmento": zod.string().describe('Segmento da pausa geral')
})

/**
 * @summary Busca produtividade
 */
export const produtividadeControllerBuscarProdutividadeParams = zod.object({
  "centerId": zod.string()
})

export const produtividadeControllerBuscarProdutividadeQueryParams = zod.object({
  "centerId": zod.string(),
  "data": zod.string(),
  "processo": zod.enum(['SEPARACAO', 'CARREGAMENTO', 'CONFERENCIA']),
  "segmento": zod.string(),
  "status": zod.string().optional(),
  "empresa": zod.string().optional(),
  "pesquisa": zod.string().optional(),
  "paginacao": zod.object({
  "page": zod.string().optional(),
  "limit": zod.string().optional()
})
})

/**
 * @summary ListarPaletesEmAberto
 */
export const listarPaletesEmAbertoParams = zod.object({
  "centerId": zod.string(),
  "data": zod.string(),
  "processo": zod.string()
})

export const listarPaletesEmAbertoResponseItem = zod.object({
  "id": zod.string(),
  "status": zod.string(),
  "criadoEm": zod.string(),
  "empresa": zod.string(),
  "quantidadeCaixas": zod.number(),
  "quantidadeUnidades": zod.number(),
  "quantidadePaletes": zod.number(),
  "enderecoVisitado": zod.number(),
  "segmento": zod.string(),
  "transporteId": zod.string(),
  "tipoProcesso": zod.string(),
  "atualizadoEm": zod.string(),
  "demandaId": zod.number().nullable(),
  "validado": zod.boolean(),
  "criadoPorId": zod.string(),
  "dataExpedicao": zod.string()
})
export const listarPaletesEmAbertoResponse = zod.array(listarPaletesEmAbertoResponseItem)

