/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Produtividade API
 * API de produtividade para gestão de produtividade dos funcionários dentro do armazém e gestão de carregamento
 * OpenAPI spec version: 1.0
 */

export type AnomaliaPorCentroZodDtoItem = {
  id?: number;
  demandaId: number;
  centerId: string;
  funcionarioId: string;
  nomeFuncionario: string;
  cadastroPorId: string;
  nomeCadastradoPor: string;
  inicio: string;
  /** @nullable */
  fim?: string | null;
  caixas: number;
  unidades: number;
  paletes: number;
  enderecosVisitado: number;
  produtividade: number;
  motivoAnomalia: string;
};
