/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Produtividade API
 * API de produtividade para gestão de produtividade dos funcionários dentro do armazém e gestão de carregamento
 * OpenAPI spec version: 1.0
 */
import type { DashCentrosZodDtoTopCincoProdutividadeItem } from './dashCentrosZodDtoTopCincoProdutividadeItem';
import type { DashCentrosZodDtoProdutividadeDiaDiaItem } from './dashCentrosZodDtoProdutividadeDiaDiaItem';
import type { DashCentrosZodDtoRankingProdutividadePorCentroItem } from './dashCentrosZodDtoRankingProdutividadePorCentroItem';
import type { DashCentrosZodDtoRankingProdutividadePorClusterItem } from './dashCentrosZodDtoRankingProdutividadePorClusterItem';

export interface DashCentrosZodDto {
  totalCaixas: number;
  horasTrabalhadas: number;
  totalDemandas: number;
  produtividade: number;
  topCincoProdutividade: DashCentrosZodDtoTopCincoProdutividadeItem[];
  produtividadeDiaDia: DashCentrosZodDtoProdutividadeDiaDiaItem[];
  rankingProdutividadePorCentro: DashCentrosZodDtoRankingProdutividadePorCentroItem[];
  rankingProdutividadePorCluster: DashCentrosZodDtoRankingProdutividadePorClusterItem[];
}
