/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Produtividade API
 * API de produtividade para gestão de produtividade dos funcionários dentro do armazém e gestão de carregamento
 * OpenAPI spec version: 1.0
 */

export type DashBoardDiaPorCentrodtoZodDtoOutputAnomaliaDemandaItem = {
  id: string;
  nome: string;
  turno: string;
  tempoDemanda: number;
  visitas: number;
  produtividade: number;
  caixas: number;
  unidade: number;
  paletes: number;
};
