/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Produtividade API
 * API de produtividade para gestão de produtividade dos funcionários dentro do armazém e gestão de carregamento
 * OpenAPI spec version: 1.0
 */
import type { DashBoardDiaPorCentrodtoZodDtoOutputOverView } from './dashBoardDiaPorCentrodtoZodDtoOutputOverView';
import type { DashBoardDiaPorCentrodtoZodDtoOutputTopCincoItem } from './dashBoardDiaPorCentrodtoZodDtoOutputTopCincoItem';
import type { DashBoardDiaPorCentrodtoZodDtoOutputPioresCincoItem } from './dashBoardDiaPorCentrodtoZodDtoOutputPioresCincoItem';
import type { DashBoardDiaPorCentrodtoZodDtoOutputAnomaliaPausaItem } from './dashBoardDiaPorCentrodtoZodDtoOutputAnomaliaPausaItem';
import type { DashBoardDiaPorCentrodtoZodDtoOutputAnomaliaDemandaItem } from './dashBoardDiaPorCentrodtoZodDtoOutputAnomaliaDemandaItem';
import type { DashBoardDiaPorCentrodtoZodDtoOutputHoraAHoraItem } from './dashBoardDiaPorCentrodtoZodDtoOutputHoraAHoraItem';

export interface DashBoardDiaPorCentrodtoZodDtoOutput {
  overView: DashBoardDiaPorCentrodtoZodDtoOutputOverView;
  topCinco: DashBoardDiaPorCentrodtoZodDtoOutputTopCincoItem[];
  pioresCinco: DashBoardDiaPorCentrodtoZodDtoOutputPioresCincoItem[];
  anomaliaPausa: DashBoardDiaPorCentrodtoZodDtoOutputAnomaliaPausaItem[];
  anomaliaDemanda: DashBoardDiaPorCentrodtoZodDtoOutputAnomaliaDemandaItem[];
  horaAHora: DashBoardDiaPorCentrodtoZodDtoOutputHoraAHoraItem[];
}
