/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Produtividade API
 * API de produtividade para gestão de produtividade dos funcionários dentro do armazém e gestão de carregamento
 * OpenAPI spec version: 1.0
 */
import type { DashUmCentrosZodDtoTopCincoProdutividadeItem } from './dashUmCentrosZodDtoTopCincoProdutividadeItem';
import type { DashUmCentrosZodDtoTopCincoPioresItem } from './dashUmCentrosZodDtoTopCincoPioresItem';
import type { DashUmCentrosZodDtoProdutividadeDiaDiaItem } from './dashUmCentrosZodDtoProdutividadeDiaDiaItem';
import type { DashUmCentrosZodDtoRankingProdutividadePorTurnoItem } from './dashUmCentrosZodDtoRankingProdutividadePorTurnoItem';
import type { DashUmCentrosZodDtoRankingProdutividadePorEmpresaItem } from './dashUmCentrosZodDtoRankingProdutividadePorEmpresaItem';

export interface DashUmCentrosZodDto {
  totalCaixas: number;
  horasTrabalhadas: number;
  totalDemandas: number;
  produtividade: number;
  topCincoProdutividade: DashUmCentrosZodDtoTopCincoProdutividadeItem[];
  topCincoPiores: DashUmCentrosZodDtoTopCincoPioresItem[];
  produtividadeDiaDia: DashUmCentrosZodDtoProdutividadeDiaDiaItem[];
  rankingProdutividadePorTurno: DashUmCentrosZodDtoRankingProdutividadePorTurnoItem[];
  rankingProdutividadePorEmpresa: DashUmCentrosZodDtoRankingProdutividadePorEmpresaItem[];
}
