/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Produtividade API
 * API de produtividade para gestão de produtividade dos funcionários dentro do armazém e gestão de carregamento
 * OpenAPI spec version: 1.0
 */

export type DemandasNaoIniciadasZodDtoOutputItem = {
  id: string;
  status: string;
  criadoEm: string;
  empresa: string;
  quantidadeCaixas: number;
  quantidadeUnidades: number;
  quantidadePaletes: number;
  enderecoVisitado: number;
  segmento: string;
  transporteId: string;
  tipoProcesso: string;
  atualizadoEm: string;
  /** @nullable */
  demandaId: number | null;
  validado: boolean;
  criadoPorId: string;
};
