/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Produtividade API
 * API de produtividade para gestão de produtividade dos funcionários dentro do armazém e gestão de carregamento
 * OpenAPI spec version: 1.0
 */
import type { FinalizarDemandaDevolucaoZodDtoCheckList } from './finalizarDemandaDevolucaoZodDtoCheckList';
import type { FinalizarDemandaDevolucaoZodDtoAnomaliaItem } from './finalizarDemandaDevolucaoZodDtoAnomaliaItem';
import type { FinalizarDemandaDevolucaoZodDtoConferenciaFisicaItem } from './finalizarDemandaDevolucaoZodDtoConferenciaFisicaItem';

export interface FinalizarDemandaDevolucaoZodDto {
  checkList: FinalizarDemandaDevolucaoZodDtoCheckList;
  anomalia?: FinalizarDemandaDevolucaoZodDtoAnomaliaItem[];
  conferenciaFisica: FinalizarDemandaDevolucaoZodDtoConferenciaFisicaItem[];
}
