/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Produtividade API
 * API de produtividade para gestão de produtividade dos funcionários dentro do armazém e gestão de carregamento
 * OpenAPI spec version: 1.0
 */

export type ListRolesEngineOutputItem = {
  /**
   * @maximum 9007199254740991
   */
  id: number;
  name: string;
  description: string;
  centerId: string;
  center?: unknown;
  enabled: boolean;
  conditions: unknown;
  /** @nullable */
  createdBy?: string | null;
};
