/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Produtividade API
 * API de produtividade para gestão de produtividade dos funcionários dentro do armazém e gestão de carregamento
 * OpenAPI spec version: 1.0
 */
import type { ProdutividadeControllerBuscarProdutividadeProcesso } from './produtividadeControllerBuscarProdutividadeProcesso';

export type ProdutividadeControllerBuscarProdutividadeParams = {
centerId: string;
data: string;
processo: ProdutividadeControllerBuscarProdutividadeProcesso;
segmento: string;
status?: string;
empresa?: string;
pesquisa?: string;
paginacao: {
  page?: string;
  limit?: string;
};
};
