/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Produtividade API
 * API de produtividade para gestão de produtividade dos funcionários dentro do armazém e gestão de carregamento
 * OpenAPI spec version: 1.0
 */

export type TransporteResponseZodDtoOutputConferencia = typeof TransporteResponseZodDtoOutputConferencia[keyof typeof TransporteResponseZodDtoOutputConferencia];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TransporteResponseZodDtoOutputConferencia = {
  NAO_INICIADO: 'NAO_INICIADO',
  EM_PROGRESSO: 'EM_PROGRESSO',
  CONCLUIDO: 'CONCLUIDO',
  EM_PAUSA: 'EM_PAUSA',
} as const;
