/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Produtividade API
 * API de produtividade para gestão de produtividade dos funcionários dentro do armazém e gestão de carregamento
 * OpenAPI spec version: 1.0
 */

export type TransporteResponseZodDtoOutputStatus = typeof TransporteResponseZodDtoOutputStatus[keyof typeof TransporteResponseZodDtoOutputStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TransporteResponseZodDtoOutputStatus = {
  AGUARDANDO_SEPARACAO: 'AGUARDANDO_SEPARACAO',
  EM_SEPARACAO: 'EM_SEPARACAO',
  SEPARACAO_CONCLUIDA: 'SEPARACAO_CONCLUIDA',
  EM_CONFERENCIA: 'EM_CONFERENCIA',
  CONFERENCIA_CONCLUIDA: 'CONFERENCIA_CONCLUIDA',
  EM_CARREGAMENTO: 'EM_CARREGAMENTO',
  CARREGAMENTO_CONCLUIDO: 'CARREGAMENTO_CONCLUIDO',
  FATURADO: 'FATURADO',
  LIBERADO_PORTARIA: 'LIBERADO_PORTARIA',
  CANCELADO: 'CANCELADO',
} as const;
