/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Produtividade API
 * API de produtividade para gestão de produtividade dos funcionários dentro do armazém e gestão de carregamento
 * OpenAPI spec version: 1.0
 */
import {
  z as zod
} from 'zod';


/**
 * @summary Dashboard de centros
 */
export const dashCentrosQueryParams = zod.object({
  "dataInicio": zod.string(),
  "dataFim": zod.string()
})

export const dashCentrosResponse = zod.object({
  "totalCaixas": zod.number(),
  "horasTrabalhadas": zod.number(),
  "totalDemandas": zod.number(),
  "produtividade": zod.number(),
  "topCincoProdutividade": zod.array(zod.object({
  "totalCaixas": zod.number(),
  "horasTrabalhadas": zod.number(),
  "cluster": zod.string(),
  "produtividade": zod.number(),
  "centro": zod.string()
})),
  "produtividadeDiaDia": zod.array(zod.object({
  "dataRegistro": zod.string(),
  "totalCaixas": zod.number(),
  "horasTrabalhadas": zod.number(),
  "produtividade": zod.number()
})),
  "rankingProdutividadePorCentro": zod.array(zod.object({
  "totalCaixas": zod.number(),
  "horasTrabalhadas": zod.number(),
  "cluster": zod.string(),
  "produtividade": zod.number(),
  "centro": zod.string()
})),
  "rankingProdutividadePorCluster": zod.array(zod.object({
  "totalCaixas": zod.number(),
  "horasTrabalhadas": zod.number(),
  "cluster": zod.string(),
  "produtividade": zod.number(),
  "centro": zod.string()
}))
})

