/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Produtividade API
 * API de produtividade para gestão de produtividade dos funcionários dentro do armazém e gestão de carregamento
 * OpenAPI spec version: 1.0
 */
import {
  z as zod
} from 'zod';


/**
 * @summary Dashboard de centros
 */
export const dashCentrosQueryParams = zod.object({
  "dataInicio": zod.string(),
  "dataFim": zod.string()
})

export const dashCentrosResponse = zod.object({
  "totalCaixas": zod.number(),
  "horasTrabalhadas": zod.number(),
  "totalDemandas": zod.number(),
  "produtividade": zod.number(),
  "topCincoProdutividade": zod.array(zod.object({
  "totalCaixas": zod.number(),
  "horasTrabalhadas": zod.number(),
  "cluster": zod.string(),
  "produtividade": zod.number(),
  "centro": zod.string()
})),
  "produtividadeDiaDia": zod.array(zod.object({
  "totalCaixas": zod.number(),
  "horasTrabalhadas": zod.number(),
  "produtividade": zod.number()
})),
  "rankingProdutividadePorCentro": zod.array(zod.object({
  "totalCaixas": zod.number(),
  "horasTrabalhadas": zod.number(),
  "cluster": zod.string(),
  "produtividade": zod.number(),
  "centro": zod.string()
})),
  "rankingProdutividadePorCluster": zod.array(zod.object({
  "totalCaixas": zod.number(),
  "horasTrabalhadas": zod.number(),
  "cluster": zod.string(),
  "produtividade": zod.number()
}))
})

/**
 * @summary Dashboard por centros
 */
export const dashCentroIndividualParams = zod.object({
  "centerId": zod.string()
})

export const dashCentroIndividualQueryParams = zod.object({
  "dataInicio": zod.string(),
  "dataFim": zod.string()
})

export const dashCentroIndividualResponse = zod.object({
  "totalCaixas": zod.number(),
  "horasTrabalhadas": zod.number(),
  "totalDemandas": zod.number(),
  "produtividade": zod.number(),
  "topCincoProdutividade": zod.array(zod.object({
  "totalCaixas": zod.number(),
  "horasTrabalhadas": zod.number(),
  "produtividade": zod.number(),
  "id": zod.string(),
  "nome": zod.string()
})),
  "topCincoPiores": zod.array(zod.object({
  "totalCaixas": zod.number(),
  "horasTrabalhadas": zod.number(),
  "produtividade": zod.number(),
  "id": zod.string(),
  "nome": zod.string()
})),
  "produtividadeDiaDia": zod.array(zod.object({
  "dataRegistro": zod.string(),
  "totalCaixas": zod.number(),
  "horasTrabalhadas": zod.number(),
  "produtividade": zod.number()
})),
  "rankingProdutividadePorTurno": zod.array(zod.object({
  "totalCaixas": zod.number(),
  "horasTrabalhadas": zod.number(),
  "produtividade": zod.number(),
  "turno": zod.string()
})),
  "rankingProdutividadePorEmpresa": zod.array(zod.object({
  "totalCaixas": zod.number(),
  "horasTrabalhadas": zod.number(),
  "produtividade": zod.number(),
  "empresa": zod.string()
}))
})

/**
 * @summary Buscar anomalias por centro
 */
export const anomaliasPorCentroParams = zod.object({
  "centerId": zod.string()
})

export const anomaliasPorCentroQueryParams = zod.object({
  "dataInicio": zod.string(),
  "dataFim": zod.string()
})

export const anomaliasPorCentroResponseItem = zod.object({
  "id": zod.number().optional(),
  "demandaId": zod.number(),
  "centerId": zod.string(),
  "funcionarioId": zod.string(),
  "nomeFuncionario": zod.string(),
  "cadastroPorId": zod.string(),
  "nomeCadastradoPor": zod.string(),
  "inicio": zod.string(),
  "fim": zod.string().nullish(),
  "caixas": zod.number(),
  "unidades": zod.number(),
  "paletes": zod.number(),
  "enderecosVisitado": zod.number(),
  "produtividade": zod.number(),
  "motivoAnomalia": zod.string()
})
export const anomaliasPorCentroResponse = zod.array(anomaliasPorCentroResponseItem)

/**
 * @summary OverViewPorDia
 */
export const overViewDiaParams = zod.object({
  "centerId": zod.string(),
  "data": zod.string(),
  "processo": zod.string()
})

export const overViewDiaResponse = zod.object({
  "overView": zod.object({
  "totalDemandas": zod.number(),
  "totalEmAndamento": zod.number(),
  "totalEmpausa": zod.number(),
  "totalFinalizado": zod.number(),
  "totalCaixas": zod.number(),
  "totalUnidades": zod.number(),
  "mediaEnderecosVisitados": zod.number()
}),
  "topCinco": zod.array(zod.object({
  "id": zod.string(),
  "nome": zod.string(),
  "turno": zod.string(),
  "caixas": zod.number(),
  "paletes": zod.number(),
  "unidades": zod.number(),
  "visitar": zod.number(),
  "produtividade": zod.number()
})),
  "pioresCinco": zod.array(zod.object({
  "id": zod.string(),
  "nome": zod.string(),
  "turno": zod.string(),
  "caixas": zod.number(),
  "paletes": zod.number(),
  "unidades": zod.number(),
  "visitar": zod.number(),
  "produtividade": zod.number()
})),
  "anomaliaPausa": zod.array(zod.object({
  "id": zod.string(),
  "nome": zod.string(),
  "turno": zod.string(),
  "motivoPausa": zod.string(),
  "tempoDePausa": zod.number()
})),
  "anomaliaDemanda": zod.array(zod.object({
  "id": zod.string(),
  "nome": zod.string(),
  "turno": zod.string(),
  "tempoDemanda": zod.number(),
  "visitas": zod.number(),
  "produtividade": zod.number(),
  "caixas": zod.number(),
  "unidade": zod.number(),
  "paletes": zod.number()
})),
  "horaAHora": zod.array(zod.object({
  "data": zod.string(),
  "caixas": zod.number(),
  "unidades": zod.number(),
  "paletes": zod.number(),
  "visitas": zod.number(),
  "produtividade": zod.number()
}))
})

